### ISSUE TITLE
Server Remembers multiple instances of each upload

### ISSUE THREAD

**Issue by QuartzShard** [QuartzShard/Turtle-Client-and-server#9]
Unsure of how to progress, do we:
Do nothing, let the list grow,
Allow only one program from each team by trimming the list in handler.py,
add a third term: program name, and allow multiple programs per team, but only one version per program name (again, trimming the list in handler.py),
add manual removal of terms in the interface,
or do nothing, and manually trim the json?

**Comment by vingard** [comment]
hey, ill speak to you guys tomorrow but would using localhost sockets not be a more efficient method of transfer for the code? also, what about the code being immediately accepted by the server and ran. if so how can we reset the environment for the code of each team without affecting other teams when they send us a new update?

anyway, its probably just me being confused by the program, ill probably understand it tomorrow.

nice work tho

**Comment by QuartzShard** [comment]
Modified Handler.py to remove duplicates from the same team
